/*
 * This file is part of HortonMachine (http://www.hortonmachine.org)
 * (C) Andrea Antonello - https://g-ant.eu
 *
 * The HortonMachine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.hortonmachine.docs;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.hortonmachine.cli.ModuleDescriptor;
import org.hortonmachine.cli.ModuleDescriptor.DataType;
import org.hortonmachine.cli.ModuleDescriptor.Parameter;
import org.hortonmachine.gears.libs.modules.HMModel;
import org.hortonmachine.gears.libs.modules.HMParameterKind;

import oms3.annotations.Bibliography;

/**
 * Generates the reference part of the manual pages of the modules from their annotations.
 *
 * <p>For each module listed in the modules list file, a Markdown fragment is written with the
 * description, the toolbox folder, the status, the keywords and the table of the parameters, all
 * read by reflection from the oms3 annotations. The narrative pages of the manual include these
 * fragments, so the module descriptions are maintained only in the code.</p>
 *
 * <p>Usage: <code>ModuleDocsGenerator &lt;modules list file&gt; &lt;output folder&gt;</code>, where the list file
 * contains a fully qualified class name per line (empty lines and lines starting with # are ignored).</p>
 *
 * @author Andrea Antonello (https://g-ant.eu)
 */
public class ModuleDocsGenerator {
    /**
     * Read the list of module classes.
     */
    public static List<String> readModulesList( File listFile ) throws Exception {
        List<String> classNames = new ArrayList<>();
        for( String line : Files.readAllLines(listFile.toPath(), StandardCharsets.UTF_8) ) {
            line = line.trim();
            if (!line.isEmpty() && !line.startsWith("#")) {
                classNames.add(line);
            }
        }
        return classNames;
    }

    /**
     * Generate the fragments of all the listed modules.
     *
     * @return the generated contents, by file name.
     */
    public static Map<String, String> generate( List<String> classNames ) throws Exception {
        Map<String, String> fileName2Content = new LinkedHashMap<>();
        for( String className : classNames ) {
            Class< ? > moduleClass = Class.forName(className);
            fileName2Content.put(moduleClass.getSimpleName() + ".md", generate(moduleClass));
        }
        return fileName2Content;
    }

    /**
     * Generate the Markdown fragment of a module.
     */
    public static String generate( Class< ? > moduleClass ) throws Exception {
        Content content = collect(moduleClass);

        StringBuilder sb = new StringBuilder();
        sb.append("<!-- Generated by ModuleDocsGenerator from the annotations of ").append(moduleClass.getName())
                .append(": do not edit, change the annotations and regenerate. -->\n\n");
        if (content.description != null) {
            sb.append(content.description).append("\n\n");
        }
        sb.append(String.join("<br>\n", content.facts)).append("\n\n");

        if (!content.inputs.isEmpty()) {
            sb.append("**Inputs**\n\n");
            sb.append("| Parameter | Type | Unit | Default | Description |\n");
            sb.append("|---|---|---|---|---|\n");
            for( String[] row : content.inputs ) {
                sb.append("| ").append(String.join(" | ", row)).append(" |\n");
            }
            sb.append("\n");
        }
        if (!content.outputs.isEmpty()) {
            sb.append("**Outputs**\n\n");
            sb.append("| Parameter | Type | Unit | Description |\n");
            sb.append("|---|---|---|---|\n");
            for( String[] row : content.outputs ) {
                sb.append("| ").append(row[0]).append(" | ").append(row[1]).append(" | ").append(row[2]).append(" | ")
                        .append(row[4]).append(" |\n");
            }
            sb.append("\n");
        }
        if (!content.references.isEmpty()) {
            sb.append("**References**\n\n");
            for( String reference : content.references ) {
                sb.append("- ").append(reference).append("\n");
            }
            sb.append("\n");
        }
        return sb.toString();
    }

    /**
     * Generate the same content as {@link #generate(Class)} as a simple HTML page,
     * as used by the help of the Spatial Toolbox.
     */
    public static String generateHtml( Class< ? > moduleClass ) throws Exception {
        Content content = collect(moduleClass);

        StringBuilder sb = new StringBuilder();
        sb.append("<html><body>");
        if (content.description != null) {
            sb.append("<p>").append(toHtml(content.description)).append("</p>");
        }
        List<String> facts = new ArrayList<>();
        for( String fact : content.facts ) {
            facts.add(toHtml(fact));
        }
        sb.append("<p>").append(String.join("<br>", facts)).append("</p>");

        if (!content.inputs.isEmpty()) {
            sb.append("<h3>Inputs</h3>");
            appendHtmlTable(sb, new String[]{"Parameter", "Type", "Unit", "Default", "Description"}, content.inputs,
                    new int[]{0, 1, 2, 3, 4});
        }
        if (!content.outputs.isEmpty()) {
            sb.append("<h3>Outputs</h3>");
            appendHtmlTable(sb, new String[]{"Parameter", "Type", "Unit", "Description"}, content.outputs,
                    new int[]{0, 1, 2, 4});
        }
        if (!content.references.isEmpty()) {
            sb.append("<h3>References</h3><ul>");
            for( String reference : content.references ) {
                sb.append("<li>").append(toHtml(reference)).append("</li>");
            }
            sb.append("</ul>");
        }
        sb.append("</body></html>");
        return sb.toString();
    }

    private static void appendHtmlTable( StringBuilder sb, String[] headers, List<String[]> rows, int[] columns ) {
        sb.append("<table cellspacing=\"0\" cellpadding=\"4\" border=\"1\"><tr>");
        for( String header : headers ) {
            sb.append("<th align=\"left\">").append(header).append("</th>");
        }
        sb.append("</tr>");
        for( String[] row : rows ) {
            sb.append("<tr>");
            for( int column : columns ) {
                sb.append("<td valign=\"top\">").append(toHtml(row[column])).append("</td>");
            }
            sb.append("</tr>");
        }
        sb.append("</table>");
    }

    /**
     * Convert the little Markdown used in the fragments (bold, code, escaped pipes) to HTML.
     */
    private static String toHtml( String markdown ) {
        String html = markdown.replace("&", "&amp;").replace("<br>", "\n").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\n", "<br>").replace("\\|", "|");
        html = html.replaceAll("\\*\\*([^*]+)\\*\\*", "<b>$1</b>");
        return html.replaceAll("`([^`]*)`", "<code>$1</code>");
    }

    /**
     * The documentation of a module, with the texts already formatted as Markdown.
     */
    private static class Content {
        String description;
        List<String> facts = new ArrayList<>();
        /** Rows of name, type, unit, default and description. */
        List<String[]> inputs = new ArrayList<>();
        List<String[]> outputs = new ArrayList<>();
        List<String> references = new ArrayList<>();
    }

    private static Content collect( Class< ? > moduleClass ) {
        ModuleDescriptor module = ModuleDescriptor.of(moduleClass.asSubclass(HMModel.class));
        Content content = new Content();
        if (!module.getDescription().isEmpty()) {
            content.description = clean(module.getDescription());
        }

        List<String> facts = content.facts;
        if (!module.getFolder().isEmpty()) {
            facts.add("**Toolbox folder:** " + module.getFolder().replace("/", " › "));
        }
        if (!module.getStatus().isEmpty()) {
            facts.add("**Status:** " + Character.toUpperCase(module.getStatus().charAt(0)) + module.getStatus().substring(1));
        }
        if (!module.getKeywords().isEmpty()) {
            facts.add("**Keywords:** " + clean(String.join(", ", module.getKeywords())));
        }
        if (!module.getAuthors().isEmpty()) {
            facts.add("**Authors:** " + clean(String.join(", ", module.getAuthors())));
        }
        facts.add("**Class:** `" + moduleClass.getName() + "`");

        for( Parameter parameter : module.getParameters() ) {
            String text = clean(parameter.description);
            // the values of enums are already in the type
            if (!parameter.choices.isEmpty() && !parameter.field.getType().isEnum()) {
                List<String> values = new ArrayList<>();
                for( String choice : parameter.choices ) {
                    values.add("`" + choice + "`");
                }
                text = text + (text.isEmpty() ? "" : " ") + "Allowed values: " + String.join(", ", values) + ".";
            }
            boolean isOutput = parameter.kind == HMParameterKind.OUTPUT;
            String[] row = new String[]{//
                    "`" + parameter.name + "`", //
                    typeName(parameter), //
                    parameter.unit != null ? clean(parameter.unit) : "", //
                    isOutput ? "" : defaultValue(parameter), //
                    text};
            if (isOutput) {
                content.outputs.add(row);
            } else {
                content.inputs.add(row);
            }
        }

        Bibliography bibliography = moduleClass.getAnnotation(Bibliography.class);
        if (bibliography != null) {
            for( String reference : bibliography.value() ) {
                if (!reference.isBlank()) {
                    content.references.add(clean(reference));
                }
            }
        }
        return content;
    }

    private static String typeName( Parameter parameter ) {
        if (parameter.isPath() && parameter.kind == HMParameterKind.OUTPUT) {
            return parameter.dataType == DataType.FOLDER ? "output folder" : "output file";
        }
        switch( parameter.dataType ) {
        case RASTER:
            return "raster file";
        case VECTOR:
            return "vector file";
        case CSV:
            return "CSV file";
        case LAS:
            return "LAS file";
        case FOLDER:
            return "folder";
        case FILE:
            return "gpkg".equals(parameter.extension) ? "GeoPackage file" : "file";
        case CRS:
            return "CRS code";
        default:
            break;
        }
        Class< ? > type = parameter.field.getType();
        if (type.isArray()) {
            return type.getComponentType().getSimpleName() + "[]";
        }
        if (type.isEnum()) {
            List<String> names = new ArrayList<>();
            for( Object constant : type.getEnumConstants() ) {
                names.add("`" + constant + "`");
            }
            return "one of: " + String.join(", ", names);
        }
        return type.getSimpleName();
    }

    private static String defaultValue( Parameter parameter ) {
        Object value = parameter.defaultValue;
        if (value == null) {
            return "";
        }
        if (value.getClass().isArray()) {
            return "array";
        }
        Class< ? > type = parameter.field.getType();
        if ((type == double.class || type == float.class) && ((Number) value).doubleValue() == 0) {
            return "`0`";
        }
        // thread defaults come from the machine generating the docs, keep the fragments machine independent
        if (type == int.class && parameter.name.toLowerCase().contains("threads")
                && ((Number) value).intValue() == HMModel.getDefaultThreadsNum()) {
            return "number of processors";
        }
        return "`" + value + "`";
    }

    /**
     * Make a text safe for a single Markdown table cell.
     */
    private static String clean( String text ) {
        return text.replace("\r", "").replace("\n", " ").replace("|", "\\|").trim();
    }

    public static void main( String[] args ) throws Exception {
        if (args.length != 2) {
            System.err.println("Usage: ModuleDocsGenerator <modules list file> <output folder>");
            System.exit(1);
        }
        File listFile = new File(args[0]);
        File outputFolder = new File(args[1]);
        outputFolder.mkdirs();
        Map<String, String> fileName2Content = generate(readModulesList(listFile));
        for( Map.Entry<String, String> entry : fileName2Content.entrySet() ) {
            Files.writeString(new File(outputFolder, entry.getKey()).toPath(), entry.getValue(), StandardCharsets.UTF_8);
        }
        System.out.println("Generated " + fileName2Content.size() + " module fragments in " + outputFolder);
    }
}
