/*
 * This file is part of HortonMachine (http://www.hortonmachine.org)
 * (C) Andrea Antonello - https://g-ant.eu
 *
 * The HortonMachine is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.hortonmachine.docs;

import java.io.File;
import java.lang.reflect.Array;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.hortonmachine.gears.libs.modules.HMConstants;
import org.hortonmachine.gears.libs.modules.HMParameterKind;

import oms3.annotations.Bibliography;
import oms3.annotations.Description;
import oms3.annotations.In;
import oms3.annotations.Keywords;
import oms3.annotations.Label;
import oms3.annotations.Out;
import oms3.annotations.Status;
import oms3.annotations.UI;
import oms3.annotations.Unit;

/**
 * Generates the reference part of the manual pages of the modules from their annotations.
 *
 * <p>For each module listed in the modules list file, a Markdown fragment is written with the
 * description, the toolbox folder, the status, the keywords and the table of the parameters, all
 * read by reflection from the oms3 annotations. The narrative pages of the manual include these
 * fragments, so the module descriptions are maintained only in the code.</p>
 *
 * <p>Usage: <code>ModuleDocsGenerator &lt;modules list file&gt; &lt;output folder&gt;</code>, where the list file
 * contains a fully qualified class name per line (empty lines and lines starting with # are ignored).</p>
 *
 * @author Andrea Antonello (https://g-ant.eu)
 */
public class ModuleDocsGenerator {
    /** Fields of the modules framework, not real parameters. */
    private static final List<String> SKIPPED_FIELDS = List.of("pm", "doProcess", "doReset");

    private static final Map<Integer, String> STATUS_NAMES = new LinkedHashMap<>();
    static {
        STATUS_NAMES.put(Status.EXPERIMENTAL, "Experimental");
        STATUS_NAMES.put(Status.DRAFT, "Draft");
        STATUS_NAMES.put(Status.TESTED, "Tested");
        STATUS_NAMES.put(Status.VALIDATED, "Validated");
        STATUS_NAMES.put(Status.CERTIFIED, "Certified");
    }

    /**
     * Read the list of module classes.
     */
    public static List<String> readModulesList( File listFile ) throws Exception {
        List<String> classNames = new ArrayList<>();
        for( String line : Files.readAllLines(listFile.toPath(), StandardCharsets.UTF_8) ) {
            line = line.trim();
            if (!line.isEmpty() && !line.startsWith("#")) {
                classNames.add(line);
            }
        }
        return classNames;
    }

    /**
     * Generate the fragments of all the listed modules.
     *
     * @return the generated contents, by file name.
     */
    public static Map<String, String> generate( List<String> classNames ) throws Exception {
        Map<String, String> fileName2Content = new LinkedHashMap<>();
        for( String className : classNames ) {
            Class< ? > moduleClass = Class.forName(className);
            fileName2Content.put(moduleClass.getSimpleName() + ".md", generate(moduleClass));
        }
        return fileName2Content;
    }

    /**
     * Generate the Markdown fragment of a module.
     */
    public static String generate( Class< ? > moduleClass ) throws Exception {
        Content content = collect(moduleClass);

        StringBuilder sb = new StringBuilder();
        sb.append("<!-- Generated by ModuleDocsGenerator from the annotations of ").append(moduleClass.getName())
                .append(": do not edit, change the annotations and regenerate. -->\n\n");
        if (content.description != null) {
            sb.append(content.description).append("\n\n");
        }
        sb.append(String.join("<br>\n", content.facts)).append("\n\n");

        if (!content.inputs.isEmpty()) {
            sb.append("**Inputs**\n\n");
            sb.append("| Parameter | Type | Unit | Default | Description |\n");
            sb.append("|---|---|---|---|---|\n");
            for( String[] row : content.inputs ) {
                sb.append("| ").append(String.join(" | ", row)).append(" |\n");
            }
            sb.append("\n");
        }
        if (!content.outputs.isEmpty()) {
            sb.append("**Outputs**\n\n");
            sb.append("| Parameter | Type | Unit | Description |\n");
            sb.append("|---|---|---|---|\n");
            for( String[] row : content.outputs ) {
                sb.append("| ").append(row[0]).append(" | ").append(row[1]).append(" | ").append(row[2]).append(" | ")
                        .append(row[4]).append(" |\n");
            }
            sb.append("\n");
        }
        if (!content.references.isEmpty()) {
            sb.append("**References**\n\n");
            for( String reference : content.references ) {
                sb.append("- ").append(reference).append("\n");
            }
            sb.append("\n");
        }
        return sb.toString();
    }

    /**
     * Generate the same content as {@link #generate(Class)} as a simple HTML page,
     * as used by the help of the Spatial Toolbox.
     */
    public static String generateHtml( Class< ? > moduleClass ) throws Exception {
        Content content = collect(moduleClass);

        StringBuilder sb = new StringBuilder();
        sb.append("<html><body>");
        if (content.description != null) {
            sb.append("<p>").append(toHtml(content.description)).append("</p>");
        }
        List<String> facts = new ArrayList<>();
        for( String fact : content.facts ) {
            facts.add(toHtml(fact));
        }
        sb.append("<p>").append(String.join("<br>", facts)).append("</p>");

        if (!content.inputs.isEmpty()) {
            sb.append("<h3>Inputs</h3>");
            appendHtmlTable(sb, new String[]{"Parameter", "Type", "Unit", "Default", "Description"}, content.inputs,
                    new int[]{0, 1, 2, 3, 4});
        }
        if (!content.outputs.isEmpty()) {
            sb.append("<h3>Outputs</h3>");
            appendHtmlTable(sb, new String[]{"Parameter", "Type", "Unit", "Description"}, content.outputs,
                    new int[]{0, 1, 2, 4});
        }
        if (!content.references.isEmpty()) {
            sb.append("<h3>References</h3><ul>");
            for( String reference : content.references ) {
                sb.append("<li>").append(toHtml(reference)).append("</li>");
            }
            sb.append("</ul>");
        }
        sb.append("</body></html>");
        return sb.toString();
    }

    private static void appendHtmlTable( StringBuilder sb, String[] headers, List<String[]> rows, int[] columns ) {
        sb.append("<table cellspacing=\"0\" cellpadding=\"4\" border=\"1\"><tr>");
        for( String header : headers ) {
            sb.append("<th align=\"left\">").append(header).append("</th>");
        }
        sb.append("</tr>");
        for( String[] row : rows ) {
            sb.append("<tr>");
            for( int column : columns ) {
                sb.append("<td valign=\"top\">").append(toHtml(row[column])).append("</td>");
            }
            sb.append("</tr>");
        }
        sb.append("</table>");
    }

    /**
     * Convert the little Markdown used in the fragments (bold, code, escaped pipes) to HTML.
     */
    private static String toHtml( String markdown ) {
        String html = markdown.replace("&", "&amp;").replace("<br>", "\n").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\n", "<br>").replace("\\|", "|");
        html = html.replaceAll("\\*\\*([^*]+)\\*\\*", "<b>$1</b>");
        return html.replaceAll("`([^`]*)`", "<code>$1</code>");
    }

    /**
     * The documentation of a module, with the texts already formatted as Markdown.
     */
    private static class Content {
        String description;
        List<String> facts = new ArrayList<>();
        /** Rows of name, type, unit, default and description. */
        List<String[]> inputs = new ArrayList<>();
        List<String[]> outputs = new ArrayList<>();
        List<String> references = new ArrayList<>();
    }

    private static Content collect( Class< ? > moduleClass ) {
        Content content = new Content();

        Description description = moduleClass.getAnnotation(Description.class);
        if (description != null) {
            content.description = clean(description.value());
        }

        List<String> facts = content.facts;
        Label label = moduleClass.getAnnotation(Label.class);
        if (label != null && !label.value().isBlank()) {
            // all modules are HortonMachine ones, the prefix of the label adds nothing
            String folder = label.value().replaceFirst("^HortonMachine/", "");
            facts.add("**Toolbox folder:** " + folder.replace("/", " › "));
        }
        Status status = moduleClass.getAnnotation(Status.class);
        if (status != null) {
            facts.add("**Status:** " + STATUS_NAMES.getOrDefault(status.value(), String.valueOf(status.value())));
        }
        Keywords keywords = moduleClass.getAnnotation(Keywords.class);
        if (keywords != null && !keywords.value().isBlank()) {
            facts.add("**Keywords:** " + clean(keywords.value()));
        }
        facts.add("**Class:** `" + moduleClass.getName() + "`");

        Object instance = null;
        try {
            instance = moduleClass.getDeclaredConstructor().newInstance();
        } catch (Exception e) {
            // without an instance the default values are not available
        }

        for( Field field : getFields(moduleClass) ) {
            boolean isIn = field.isAnnotationPresent(In.class);
            boolean isOut = field.isAnnotationPresent(Out.class);
            if ((!isIn && !isOut) || SKIPPED_FIELDS.contains(field.getName())) {
                continue;
            }
            UI ui = field.getAnnotation(UI.class);
            String uiHint = ui != null ? ui.value() : "";
            if (uiHint.contains(HMConstants.HIDE_UI_HINT)) {
                continue;
            }
            Description fieldDescription = field.getAnnotation(Description.class);
            Unit unit = field.getAnnotation(Unit.class);
            String text = fieldDescription != null ? clean(fieldDescription.value()) : "";
            String choices = comboValues(uiHint);
            if (choices != null) {
                text = text + (text.isEmpty() ? "" : " ") + "Allowed values: " + choices + ".";
            }
            boolean isOutput = HMParameterKind.of(isIn, isOut, uiHint) == HMParameterKind.OUTPUT;
            String[] row = new String[]{//
                    "`" + field.getName() + "`", //
                    typeName(field, uiHint), //
                    unit != null ? clean(unit.value()) : "", //
                    isIn && !isOutput ? defaultValue(field, instance) : "", //
                    text};
            if (isOutput) {
                content.outputs.add(row);
            } else {
                content.inputs.add(row);
            }
        }

        Bibliography bibliography = moduleClass.getAnnotation(Bibliography.class);
        if (bibliography != null) {
            for( String reference : bibliography.value() ) {
                if (!reference.isBlank()) {
                    content.references.add(clean(reference));
                }
            }
        }
        return content;
    }

    /**
     * @return the public fields of the class, from the topmost superclass down, each in declaration order.
     *         A field redeclared in a subclass hides the inherited one, keeping its position: wrappers
     *         that extend their Oms module redeclare the coverages as file paths.
     */
    private static List<Field> getFields( Class< ? > moduleClass ) {
        List<Class< ? >> hierarchy = new ArrayList<>();
        for( Class< ? > c = moduleClass; c != null && c != Object.class; c = c.getSuperclass() ) {
            hierarchy.add(0, c);
        }
        Map<String, Field> fields = new LinkedHashMap<>();
        for( Class< ? > c : hierarchy ) {
            for( Field field : c.getDeclaredFields() ) {
                if (Modifier.isPublic(field.getModifiers()) && !Modifier.isStatic(field.getModifiers())) {
                    fields.put(field.getName(), field);
                }
            }
        }
        return new ArrayList<>(fields.values());
    }

    private static String typeName( Field field, String uiHint ) {
        if (uiHint.contains(HMConstants.FILEIN_UI_HINT_RASTER)) {
            return "raster file";
        } else if (uiHint.contains(HMConstants.FILEIN_UI_HINT_VECTOR)) {
            return "vector file";
        } else if (uiHint.contains(HMConstants.FILEIN_UI_HINT_CSV)) {
            return "CSV file";
        } else if (uiHint.contains(HMConstants.FILEIN_UI_HINT_LAS)) {
            return "LAS file";
        } else if (uiHint.contains(HMConstants.FOLDEROUT_UI_HINT)) {
            return "output folder";
        } else if (uiHint.contains(HMConstants.FILEOUT_UI_HINT)) {
            return "output file";
        } else if (uiHint.contains(HMConstants.FOLDERIN_UI_HINT)) {
            return "folder";
        } else if (uiHint.contains(HMConstants.FILEIN_UI_HINT_GENERIC)) {
            return "file";
        } else if (uiHint.contains(HMConstants.CRS_UI_HINT)) {
            return "CRS code";
        }
        Class< ? > type = field.getType();
        if (type.isArray()) {
            return type.getComponentType().getSimpleName() + "[]";
        }
        if (type.isEnum()) {
            return "one of: " + enumValues(type);
        }
        return type.getSimpleName();
    }

    /**
     * @return the allowed values of a combo UI hint (combo:value1,value2,...), or null.
     */
    private static String comboValues( String uiHint ) {
        for( String hint : uiHint.split(";") ) {
            hint = hint.trim();
            if (hint.startsWith(HMConstants.COMBO_UI_HINT + ":")) {
                List<String> values = new ArrayList<>();
                for( String value : hint.substring(HMConstants.COMBO_UI_HINT.length() + 1).split(",") ) {
                    values.add("`" + value.trim() + "`");
                }
                return String.join(", ", values);
            }
        }
        return null;
    }

    private static String enumValues( Class< ? > enumType ) {
        List<String> names = new ArrayList<>();
        for( Object constant : enumType.getEnumConstants() ) {
            names.add("`" + constant + "`");
        }
        return String.join(", ", names);
    }

    private static String defaultValue( Field field, Object instance ) {
        if (instance == null) {
            return "";
        }
        try {
            Object value = field.get(instance);
            if (value == null) {
                return "";
            }
            if (value.getClass().isArray()) {
                return Array.getLength(value) == 0 ? "" : "array";
            }
            if (value instanceof String && ((String) value).isEmpty()) {
                return "";
            }
            if ((field.getType() == double.class || field.getType() == float.class) && ((Number) value).doubleValue() == 0) {
                return "`0`";
            }
            return "`" + value + "`";
        } catch (Exception e) {
            return "";
        }
    }

    /**
     * Make a text safe for a single Markdown table cell.
     */
    private static String clean( String text ) {
        return text.replace("\r", "").replace("\n", " ").replace("|", "\\|").trim();
    }

    public static void main( String[] args ) throws Exception {
        if (args.length != 2) {
            System.err.println("Usage: ModuleDocsGenerator <modules list file> <output folder>");
            System.exit(1);
        }
        File listFile = new File(args[0]);
        File outputFolder = new File(args[1]);
        outputFolder.mkdirs();
        Map<String, String> fileName2Content = generate(readModulesList(listFile));
        for( Map.Entry<String, String> entry : fileName2Content.entrySet() ) {
            Files.writeString(new File(outputFolder, entry.getKey()).toPath(), entry.getValue(), StandardCharsets.UTF_8);
        }
        System.out.println("Generated " + fileName2Content.size() + " module fragments in " + outputFolder);
    }
}
