name: Build and Test Branch

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build and Test Branch
        run: |
          mvn --no-transfer-progress \
            --batch-mode \
            clean install \
            -Dmaven.javadoc.skip=true
